{
 "title": "Dashboard App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c23-tp-1_node_1, 1c23-tp-1_node_2, 1c23-tp-1_node_3, 1c23-tp-1_cadvisor_1, 1c23-tp-1_grafana_1, 1c23-tp-1_graphite_1,  1c23-tp-1_nginx_1, 1c23-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Tiempo de respuesta de la API (/www.aviationweather.gov) vs Endpoint de /metar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.timers.app.endpoint.metar.timing.*), \"endpoint\")"
    },
    {
     "target": "alias(sumSeries(stats.timers.api.metar.timing.*), \"api\")"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta de la API (/api.spaceflightnewsapi.net) vs Endpoint de /space_news",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.timers.app.endpoint.space_news.timing.*), \"endpoint\")"
    },
    {
     "target": "alias(sumSeries(stats.timers.api.space_news.timing.*), \"api\")"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta de las APIs utilizadas por los endpoints /fact, /space_news y /metar",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(color(sumSeries(stats.timers.api.fact.timing.*), \"red\"), \"fact\")\n\n"
    },
    {
     "target": "alias(color(sumSeries(stats.timers.api.space_news.timing.*), \"blue\"), \"space-news\")\n"
    },
    {
     "target": "alias(color(sumSeries(stats.timers.api.metar.timing.*), \"green\"), \"metar\")"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta de la API (/uselessfacts) vs Endpoint de /fact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(color(sumSeries(stats.timers.app.endpoint.fact.timing.*), \"red\"), \"endpoint\")"
    },
    {
     "target": "alias(color(sumSeries(stats.timers.api.fact.timing.*), \"blue\"), \"api\")"
    }
   ]
  },
  {
   "title": "Comparación del tiempo de respuesta con y sin caché en el endpoint /fact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.timers.app.endpoint.fact_no_cache.timing.*), \"no cached\")"
    },
    {
     "target": "alias(sumSeries(stats.timers.app.endpoint.fact.timing.*), \"cached\")"
    }
   ]
  },
  {
   "title": "Monitoreo del tiempo de respuesta de los endpoints /fact, /space_news y /metar en tiempo real",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(color(sumSeries(stats.timers.app.endpoint.fact.timing.*), \"red\"), \"fact\")"
    },
    {
     "target": "alias(color(sumSeries(stats.timers.app.endpoint.space_news.timing.*), \"red\"), \"space-news\")"
    },
    {
     "target": "alias(color(sumSeries(stats.timers.app.endpoint.metar.timing.*), \"red\"), \"metar\")"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 17179869184), 'Memory')"
    }
   ]
  }
 ]
}